### ISSUE TITLE
Crash when using  token with "copy fixdat"

### ISSUE THREAD

**Issue by Djabal** [emmercm/igir#1200]
### Paste the command

igir copy fixdat  --dat Microsoft\ -\ MSX\ \(20231222-131915\).dat  --input ./Microsoft\ -\ MSX --output "./{batocera}/"

### Describe the bug

Igir crash when using the commands copy and fixdat together (work too with move and fixdat, maybe with other couples) with any tokens except datName and datDescription.

### Expected behavior

Igir don't crash.

But to go farther, a expected behavior for the tokens should be :
If : 
- **a token is wrong / doesn't exist** : stop and write a correct error ("No token named xxx").
- **a token cannot be expanded for the current dat** : write an error after the dat name ("✓ Nintendo - Game Boy ········ |No files written, token cannot be expanded")
- - **a token cannot be expanded for the current roms/bios** : write an error after the dat name ("✓ Nintendo - Game Boy ········ |Some files hasn't be written, token cannot be expanded")
Should I open a discussion ?

### Debug logs

```
[14:45:05.309] TRACE: Parsing CLI arguments: copy fixdat --dat "Microsoft - MSX (20231222-131915).dat" --input "./Microsoft - MSX" --output ./{batocera}/ -vvv
[14:45:05.310] TRACE: Parsed CLI options: {"_":["copy","fixdat"],"fixdat":false,"input":["./Microsoft - MSX"],"inputExclude":[],"inputMinChecksum":"CRC32","inputChecksumArchives":"auto","dat":["Microsoft - MSX (20231222-131915).dat"],"datExclude":[],"datRegex":"","datNameRegex":"","datRegexExclude":"","datNameRegexExclude":"","datDescriptionRegex":"","datDescriptionRegexExclude":"","datCombine":false,"datIgnoreParentClone":false,"patch":[],"patchExclude":[],"output":"./{batocera}/","dirMirror":false,"dirDatName":false,"dirDatDescription":false,"dirLetter":false,"dirLetterCount":1,"dirLetterLimit":0,"dirLetterGroup":false,"dirGameSubdir":"multiple","overwrite":false,"overwriteInvalid":false,"cleanExclude":[],"cleanDryRun":false,"zipExclude":"","zipDatName":false,"symlink":false,"symlinkRelative":false,"header":"","mergeRoms":"fullnonmerged","allowIncompleteSets":false,"filterRegex":"","filterRegexExclude":"","filterLanguage":[],"languageFilter":[],"filterRegion":[],"regionFilter":[],"noBios":false,"onlyBios":false,"noDevice":false,"onlyDevice":false,"noUnlicensed":false,"onlyUnlicensed":false,"onlyRetail":false,"noDebug":false,"onlyDebug":false,"noDemo":false,"onlyDemo":false,"noBeta":false,"onlyBeta":false,"noSample":false,"onlySample":false,"noPrototype":false,"onlyPrototype":false,"noProgram":false,"onlyProgram":false,"noAftermarket":false,"onlyAftermarket":false,"noHomebrew":false,"onlyHomebrew":false,"noUnverified":false,"onlyUnverified":false,"noBad":false,"onlyBad":false,"single":false,"preferGameRegex":"","preferRomRegex":"","preferVerified":false,"preferGood":false,"preferLanguage":[],"preferRegion":[],"preferRevisionNewer":false,"preferRevisionOlder":false,"preferRetail":false,"preferNtsc":false,"preferPal":false,"preferParent":false,"reportOutput":"./igir_%YYYY-%MM-%DDT%HH:%mm:%ss.csv","datThreads":3,"readerThreads":8,"writerThreads":4,"writeRetry":2,"tempDir":"/tmp/igir/20240706-144505","disableCache":false,"verbose":3,"help":false,"d":["Microsoft - MSX (20231222-131915).dat"],"i":["./Microsoft - MSX"],"o":"./{batocera}/","v":3,"input-min-checksum":"CRC32","input-checksum-archives":"auto","dir-letter-count":1,"dir-game-subdir":"multiple","merge-roms":"fullnonmerged","report-output":"./igir_%YYYY-%MM-%DDT%HH:%mm:%ss.csv","dat-threads":3,"reader-threads":8,"writer-threads":4,"write-retry":2,"$0":"igir"}
[14:45:05.355] TRACE: loading the file cache at '/home/morgan/igir.cache'
[14:45:05.365] TRACE: DATScanner: scanning DAT files
[14:45:05.389] TRACE: DATScanner: found 1 DAT file
[14:45:05.390] TRACE: DATScanner: enumerating DAT archives
[14:45:05.398] TRACE: DATScanner: parsing 1 DAT file
[14:45:05.401] TRACE: DATScanner: Microsoft - MSX (20231222-131915).dat: attempting to parse 265.2KB of XML
[14:45:05.450] TRACE: DATScanner: Microsoft - MSX (20231222-131915).dat: parsed XML, deserializing to DAT
[14:45:05.529] TRACE: DATScanner: Microsoft - MSX (20231222-131915).dat: 38.6MB of 943 games, 943 parents parsed
[14:45:05.533] TRACE: DATScanner: done scanning DAT files
✓ Scanning for DATs ·········· | 1 DAT found
[14:45:05.543] TRACE: ROMScanner: scanning ROM files
[14:45:05.551] TRACE: ROMScanner: found 1 ROM file
[14:45:05.568] TRACE: ROMScanner: done scanning ROM files
[14:45:05.568] TRACE: ROMHeaderProcessor: processing file headers
[14:45:05.570] TRACE: ROMHeaderProcessor: found headers in 0 ROMs
[14:45:05.570] TRACE: ROMHeaderProcessor: done processing file headers
[14:45:05.570] TRACE: ROMIndexer: indexing 1 file
[14:45:05.572] TRACE: ROMIndexer: found 1 unique file
[14:45:05.572] TRACE: ROMIndexer: done indexing files
✓ Scanning for ROMs ·········· | 1 file found
[14:45:05.573] TRACE: processing 1 DAT
[14:45:05.574] TRACE: DATParentInferrer: Microsoft - MSX: inferring parents for 943 games
[14:45:05.636] TRACE: DATParentInferrer: Microsoft - MSX: grouped to 628 parents
[14:45:05.636] TRACE: DATParentInferrer: done inferring parents943
[14:45:05.636] TRACE: DATMergerSplitter: Microsoft - MSX: merging & splitting 943 games
[14:45:05.645] TRACE: DATMergerSplitter: Microsoft - MSX: merged/split to 943 games
[14:45:05.645] TRACE: DATMergerSplitter: Microsoft - MSX: done merging & splitting
[14:45:05.645] TRACE: DATFilter: Microsoft - MSX: filtering DAT
[14:45:05.651] TRACE: DATFilter: Microsoft - MSX: filtered to 943/943 games (38.6MB)
[14:45:05.651] TRACE: DATFilter: Microsoft - MSX: done filtering DAT
[14:45:05.652] TRACE: CandidateGenerator: Microsoft - MSX: generating candidates
[14:45:05.660] TRACE: CandidateGenerator: Microsoft - MSX: [BIOS] Kanji Rom - JIS 1st Class (Japan): found 0 candidates
[14:45:05.660] TRACE: CandidateGenerator: Microsoft - MSX: [BIOS] Kanji Rom - JIS 1st Class (Japan) (parent): found 0 candidates
[14:45:05.660] TRACE: CandidateGenerator: Microsoft - MSX: 10-Yard Fight (Japan): found 0 candidates
[...]
[14:45:05.767] TRACE: CandidateGenerator: Microsoft - MSX: Zexas Limited (Japan) (parent): found 0 candidates
[14:45:05.770] TRACE: CandidateGenerator: Microsoft - MSX: Wing Man 2 (Japan): found 1 candidate
[14:45:05.770] TRACE: CandidateGenerator: Microsoft - MSX: Wing Man 2 (Japan) (parent): found 1 candidate
[14:45:05.771] TRACE: CandidateGenerator: Microsoft - MSX: generated 128KB of 1 candidate for 628 parents
[14:45:05.771] TRACE: CandidateGenerator: Microsoft - MSX: done generating candidates
[14:45:05.771] TRACE: CandidatePatchGenerator: Microsoft - MSX: generating patched candidates
[14:45:05.905] TRACE: CandidatePatchGenerator: Microsoft - MSX: 0 unique patches found
[14:45:05.910] TRACE: CandidatePatchGenerator: Microsoft - MSX: done generating patched candidates
[14:45:05.911] TRACE: CandidatePreferer: Microsoft - MSX: preferring candidates
[14:45:05.911] TRACE: CandidatePreferer: Microsoft - MSX: not running in single/1G1R mode, not preferring candidates
[14:45:05.911] TRACE: CandidateArchiveFileHasher: Microsoft - MSX: not testing or overwriting invalid files, no need
[14:45:05.912] TRACE: CandidatePostProcessor: Microsoft - MSX: processing candidates
[14:45:05.918] TRACE: CandidatePostProcessor: Microsoft - MSX: done processing candidates
[14:45:05.918] TRACE: CandidateMergeSplitValidator: Microsoft - MSX: validating merged & split ROM sets
[14:45:05.920] TRACE: CandidateMergeSplitValidator: Microsoft - MSX: done validating merged & split ROM sets
[14:45:05.921] TRACE: CandidateWriter: Microsoft - MSX: writing 1 candidate
[14:45:05.922] TRACE: CandidateWriter: Microsoft - MSX: Wing Man 2 (Japan) (parent): writing 1 candidate
[14:45:05.923] TRACE: CandidateWriter: Microsoft - MSX: Wing Man 2 (Japan): no zip archives to write
[14:45:05.924] TRACE: CandidateWriter: Microsoft - MSX: Wing Man 2 (Japan): writing 0B of 1 file
[14:45:05.924] DEBUG: CandidateWriter: Microsoft - MSX: Wing Man 2 (Japan): msx1/Wing Man 2 (Japan).zip: not overwriting existing file
[14:45:05.924] TRACE: CandidateWriter: Microsoft - MSX: Wing Man 2 (Japan) (parent): done writing 1 candidate
[14:45:05.924] TRACE: CandidateWriter: Microsoft - MSX: done writing 1 candidate
[14:45:05.925] TRACE: FixdatCreator: Microsoft - MSX: generating a fixdat
Processing DATs ·············· | ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ | 0/1
✎ Microsoft - MSX ············ | ░░░░░░░░░░░░░░░░░░░░░░░░░ | 0/1file:///tmp/caxa/applications/igir/xhpuc4rlsc/0/dist/src/types/outputFactory.js:115
            throw new Error(`failed to replace output token${leftoverTokens.length !== 1 ? 's' : ''}: ${leftoverTokens.join(', ')}`);
                  ^

Error: failed to replace output token: {batocera}
    at OutputFactory.replaceTokensInOutputPath (file:///tmp/caxa/applications/igir/xhpuc4rlsc/0/dist/src/types/outputFactory.js:115:19)
    at OutputFactory.getDir (file:///tmp/caxa/applications/igir/xhpuc4rlsc/0/dist/src/types/outputFactory.js:83:49)
    at FixdatCreator.<anonymous> (file:///tmp/caxa/applications/igir/xhpuc4rlsc/0/dist/src/modules/fixdatCreator.js:53:33)
    at Generator.next (<anonymous>)
    at fulfilled (file:///tmp/caxa/applications/igir/xhpuc4rlsc/0/dist/src/modules/fixdatCreator.js:4:58)

Node.js v20.15.0
```

### DAT(s) used

any dat, i use No-Intro standard (2024-06-18)

### igir version

v2.9.1

### Node.js version

N/A

### Operating system

Debian

**Comment by emmercm** [comment]
Confirmed that this is a problem, and it only happens when using one of the writing commands at the same time as the `fixdat` command.
