### ISSUE TITLE
ERROR: x.zip: written zip failed to get archive contents: Error: ENOENT: no such file or directory, stat 'x.zip'

### ISSUE THREAD

**Issue by veraciousnottaken** [emmercm/igir#341]
### Paste the command

```
sudo ./igir move zip test report --input "RomsTestGB" --output "./No-IntroGB" --dat ./Nintendo\ -\ Game\ Boy\ \(Parent-Clone\)\ \(20230318-005235\).zip --single --prefer-language EN --prefer-region USA,EUR,WORLD,JPN --dir-dat-name --overwrite -vv
```

### Describe the bug

First: start with empty `No-IntroGB' folder and 5 files in `RomsTestGB\gb`. Result: pass, I mean 5 files transferred and renamed

```
INFO:  DATScanner: Scanning DAT files
DEBUG: DATScanner: Found 1 DAT file
DEBUG: DATScanner: Enumerating DAT archives
DEBUG: DATScanner: Deserializing DAT XML to objects
DEBUG: DATScanner: Parsing DAT files
INFO:  DATScanner: Done scanning DAT files
✓ Scanning for DATs ············ | 1 unique DAT found
INFO:  ROMScanner: Scanning ROM files
DEBUG: ROMScanner: Found 5 ROM files
INFO:  ROMScanner: Done scanning ROM files
✓ Scanning for ROMs ············ | 5 unique ROMs found
INFO:  HeaderProcessor: Processing file headers
INFO:  HeaderProcessor: Done processing file headers
✓ Detecting ROM headers ········ | 5 ROMs processed
INFO:  Processing 1 DAT
INFO:  CandidateFilter: Nintendo - Game Boy: Generating candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: 5 unique ROMs found
DEBUG: CandidateFilter: Nintendo - Game Boy: generated 1.1MiB of 9 candidates for 1,338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done generating candidates
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Generating patched candidates
DEBUG: PatchCandidateGenerator: Nintendo - Game Boy: 0 unique patches found
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Done generating patched candidates
INFO:  CandidateFilter: Nintendo - Game Boy: Filtering candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: filtered to 640KiB of 5 candidates for 1,338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done filtering candidates
INFO:  ROMWriter: Nintendo - Game Boy: Writing candidates
DEBUG: ROMWriter: Nintendo - Game Boy: Deleting moved files
INFO:  ROMWriter: Nintendo - Game Boy: Done writing candidates 0/1,338
INFO:  StatusGenerator: Nintendo - Game Boy: Generating ROM statuses
INFO:  StatusGenerator: Nintendo - Game Boy: Done generating ROM statuses
✓ Nintendo - Game Boy ·········· | 0/3 BIOSes, 5/1,672 retail releases written
INFO:  Done processing 1 DAT
INFO:  ReportGenerator: Generating report
DEBUG: ReportGenerator: No-IntroGB/igir_2023-03-22T13;26;54+01;00.csv: wrote 1 status
INFO:  ReportGenerator: Done generating report
✓ Generating report ············ | No-IntroGB/igir_2023-03-22T13;26;54+01;00.csv
```

Second: fill RomsTestGB\gb again with the same original files (cartridges dumps) and rerun the same command, also `No-IntroGB` now has `Nintendo - Game Boy` in it and 5 files, result: some errors:

```
INFO:  DATScanner: Scanning DAT files
DEBUG: DATScanner: Found 1 DAT file
DEBUG: DATScanner: Enumerating DAT archives
DEBUG: DATScanner: Deserializing DAT XML to objects
DEBUG: DATScanner: Parsing DAT files
INFO:  DATScanner: Done scanning DAT files
✓ Scanning for DATs ············ | 1 unique DAT found
INFO:  ROMScanner: Scanning ROM files
DEBUG: ROMScanner: Found 5 ROM files
INFO:  ROMScanner: Done scanning ROM files
✓ Scanning for ROMs ············ | 5 unique ROMs found
INFO:  HeaderProcessor: Processing file headers
INFO:  HeaderProcessor: Done processing file headers
✓ Detecting ROM headers ········ | 5 ROMs processed
INFO:  Processing 1 DAT
INFO:  CandidateFilter: Nintendo - Game Boy: Generating candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: 5 unique ROMs found
DEBUG: CandidateFilter: Nintendo - Game Boy: generated 1.1MiB of 9 candidates for 1,338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done generating candidates
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Generating patched candidates
DEBUG: PatchCandidateGenerator: Nintendo - Game Boy: 0 unique patches found
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Done generating patched candidates
INFO:  CandidateFilter: Nintendo - Game Boy: Filtering candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: filtered to 640KiB of 5 candidates for 1,338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done filtering candidates
INFO:  ROMWriter: Nintendo - Game Boy: Writing candidates
ERROR: ROMWriter: Nintendo - Game Boy: No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip: written zip failed to get archive contents: Error: ENOENT: no such file or directory, stat 'No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip'
DEBUG: ROMWriter: Nintendo - Game Boy: Deleting moved files
INFO:  ROMWriter: Nintendo - Game Boy: Done writing candidates 1,333/1,338
INFO:  StatusGenerator: Nintendo - Game Boy: Generating ROM statuses
INFO:  StatusGenerator: Nintendo - Game Boy: Done generating ROM statuses
✓ Nintendo - Game Boy ·········· | 0/3 BIOSes, 5/1,672 retail releases written
INFO:  Done processing 1 DAT
INFO:  ReportGenerator: Generating report
DEBUG: ReportGenerator: No-IntroGB/igir_2023-03-22T13;29;04+01;00.csv: wrote 1 status
INFO:  ReportGenerator: Done generating report
✓ Generating report ············ | No-IntroGB/igir_2023-03-22T13;29;04+01;00.csv
```

So, the same file `Addams Family, The (USA)` first was moved and processed properly and second time not.

### Expected behavior

When specifying move and overwrite I expect `igir` to move all supported files.

### Debug logs

Report content from first and second run:

```csv
Nintendo - Game Boy,"Addams Family, The (USA)",FOUND,"No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip",false,false,true,false,false,false,false,false,false,false,false,false
```

### igir version

1.4.1

### Node.js version

12.22.9

### Operating system

WSL Ubuntu

**Comment by emmercm** [comment]
Hi @veraciousnottaken, could you show the contents of the input directory before each command, and the output directory after each command?

Could you run the command with one more level of verbosity, `-vvv`?

Does `No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip` exist after the second write? What are its contents?

**Comment by veraciousnottaken** [comment]
I hope I found a solution (and my error), in the command when `--inputs` is "dir" then there's problem with left files, but when `--inputs` is "./dir" all files are moved. But no, repeating command with "./dir" sometimes moves all files, sometime one file is left. There's no rule that file that isn't moved is always the same.

Steps to reproduce:
`No-IntroGB` empty

```
U:\RETRO\ROMSTESTGB
└───gb
        4-in-1 Fun Pak (USA, Europe).zip
        4-in-1 Fun Pak Volume II (USA, Europe).zip
        Addams Family, The (USA).zip
        Addams Family, The - Pugsley's Scavenger Hunt (USA, Europe).zip
        Adventure Island (USA, Europe).zip
```

"wrong command" without "./"
`/mnt/u/Retro$ sudo ./igir move zip test report --input "RomsTestGB" --output "./No-IntroGB" --dat ./Nintendo\ -\ Game\ Boy\ \(Parent-Clone\)\ \(20230318-005235\).zip --single --prefer-language EN --prefer-region USA,EUR,WORLD,JPN --dir-dat-name --overwrite -vvv`

```
U:\RETRO\NO-INTROGB
│   igir_2023-03-23T09;24;34+01;00.csv
│
└───Nintendo - Game Boy
        4-in-1 Fun Pak (USA, Europe).zip
        4-in-1 Funpak - Volume II (USA, Europe).zip
        Addams Family, The (USA).zip
        Addams Family, The - Pugsley's Scavenger Hunt (USA, Europe).zip
        Adventure Island (USA, Europe).zip
```

```
U:\RETRO\ROMSTESTGB
└───gb
        Addams Family, The - Pugsley's Scavenger Hunt (USA, Europe).zip
```
[wrong command log.log](https://github.com/emmercm/igir/files/11048607/wrong.command.log.log)

After command

`/mnt/u/Retro$ sudo ./igir move zip test report --input "./RomsTestGB" --output "./No-IntroGB" --dat ./Nintendo\ -\ Game\ Boy\ \(Parent-Clone\)\ \(20230318-005235\).zip --single --prefer-language EN --prefer-region USA,EUR,WORLD,JPN --dir-dat-name --overwrite -v`

`"u:\Retro\RomsTestGB\gb\Adventure Island (USA, Europe).zip"` is left in `--inputs` directory.
 
[other file left.log](https://github.com/emmercm/igir/files/11048673/other.file.left.log)

Files from source directory:
```
4-in-1 Fun Pak (USA, Europe).gb
4-in-1 Fun Pak Volume II (USA, Europe).gb
Addams Family, The (USA).gb
Addams Family, The - Pugsley's Scavenger Hunt (USA, Europe).gb
Adventure Island (USA, Europe).gb
```

**Comment by emmercm** [comment]
I think I understand now. So the issue, overall, is that files are still left in the input directory even though they have been "moved" to the output directory - and it doesn't seem deterministic what files are leftover in the input. Does that sound about right?

**Comment by emmercm** [comment]
From the second run in the original post:

```
ERROR: ROMWriter: Nintendo - Game Boy: No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip: written zip failed to get archive contents: Error: ENOENT: no such file or directory, stat 'No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip'
```

`igir` won't delete files from the input directory if it believes their write has failed.

In that case, did the write actually succeed?

**Comment by veraciousnottaken** [comment]
> I think I understand now. So the issue, overall, is that files are still left in the input directory even though they have been "moved" to the output directory - and it doesn't seem deterministic what files are leftover in the input. Does that sound about right?

Correct.

> From the second run in the original post:
> 
> ```
> ERROR: ROMWriter: Nintendo - Game Boy: No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip: written zip failed to get archive contents: Error: ENOENT: no such file or directory, stat 'No-IntroGB/Nintendo - Game Boy/Addams Family, The (USA).zip'
> ```
> 
> `igir` won't delete files from the input directory if it believes their write has failed.
> 
> In that case, did the write actually succeed?

Write was created correctly. ZIP file in output directory is re-compressed but content is byte-to-byte equal to content in input directory.

**Comment by emmercm** [comment]
I wonder if there is something funny with file mounts / slow file flushing because of WSL. My hypothesis is that zip creation might not be waiting for the file to finish writing before moving on, which might lead to the "file doesn't exist [right now]" error even though it wrote fine (eventually).

**Comment by emmercm** [comment]
Note to self, I wonder if this issue is why I sometimes see issues for Windows CI:

```text
   ● zip › should write one zip with all ROMs for zip-dat-name: raw/*

    FILE_ENDED

      at PullStream.pull (node_modules/unzipper/lib/PullStream.js:83:28)
      at PullStream.<anonymous> (node_modules/unzipper/lib/PullStream.js:20:10)
```

https://github.com/emmercm/igir/actions/runs/4544719609/jobs/8011124351?pr=336

**Comment by emmercm** [comment]
Could you check if v1.5.0 fixes your problem @veraciousnottaken?

**Comment by veraciousnottaken** [comment]
I think it's fixed:

```
P:\Retro\igir-tests>igir move zip test --input RomsTestGB --output No-IntroGB  --dat "Nintendo - Game Boy (Parent-Clone) (20230318-005235).zip" --single --overwrite -vv --dir-dat-name
 ______   ______   ______  _______
|      \ /      \ |      \|       \
 \$$$$$$|  $$$$$$\ \$$$$$$| $$$$$$$\
  | $$  | $$ __\$$  | $$  | $$__| $$
  | $$  | $$|    \  | $$  | $$    $$   ROM collection manager
  | $$  | $$ \$$$$  | $$  | $$$$$$$\
 _| $$_ | $$__| $$ _| $$_ | $$  | $$   v1.5.0
|   $$ \ \$$    $$|   $$ \| $$  | $$
 \$$$$$$  \$$$$$$  \$$$$$$ \$$   \$$


INFO:  DATScanner: Scanning DAT files
DEBUG: DATScanner: Found 1 DAT file
DEBUG: DATScanner: Enumerating DAT archives
DEBUG: DATScanner: Deserializing DAT XML to objects
DEBUG: DATScanner: Parsing DAT files
INFO:  DATScanner: Done scanning DAT files
√ Scanning for DATs ············ | 1 unique DAT found
INFO:  ROMScanner: Scanning ROM files
DEBUG: ROMScanner: Found 5 ROM files
INFO:  ROMScanner: Done scanning ROM files
√ Scanning for ROMs ············ | 5 unique ROMs found
INFO:  HeaderProcessor: Processing file headers
INFO:  HeaderProcessor: Done processing file headers
√ Detecting ROM headers ········ | 5 ROMs processed
INFO:  Processing 1 DAT
INFO:  CandidateFilter: Nintendo - Game Boy: Generating candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: 5 unique ROMs found
DEBUG: CandidateFilter: Nintendo - Game Boy: generated 1.1MiB of 9 candidates for 1338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done generating candidates
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Generating patched candidates
DEBUG: PatchCandidateGenerator: Nintendo - Game Boy: 0 unique patches found
INFO:  PatchCandidateGenerator: Nintendo - Game Boy: Done generating patched candidates
INFO:  CandidateFilter: Nintendo - Game Boy: Filtering candidates
DEBUG: CandidateFilter: Nintendo - Game Boy: filtered to 640KiB of 5 candidates for 1338 parents
INFO:  CandidateFilter: Nintendo - Game Boy: Done filtering candidates
INFO:  ROMWriter: Nintendo - Game Boy: writing 5 candidates
DEBUG: ROMWriter: Nintendo - Game Boy: deleting 5 moved files
INFO:  ROMWriter: Nintendo - Game Boy: done writing 5 candidates/1338
INFO:  StatusGenerator: Nintendo - Game Boy: Generating ROM statuses
INFO:  StatusGenerator: Nintendo - Game Boy: Done generating ROM statuses
√ Nintendo - Game Boy ·········· | 0/3 BIOSes, 5/1672 retail releases written
INFO:  Done processing 1 DAT
√ Processing DATs ·············· | 1 DAT processed
```

unfortunately error described in [#347](https://github.com/emmercm/igir/discussions/347) still appears

**Comment by emmercm** [comment]
I'll head back to #347 to see if we can find out what's wrong.
